name: process_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=11.0.0
  - pip:
      - wandb == 0.13.5  #  - wandb==0.10.21
      # - protobuf==3.20.* 