name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.2.2
  - hydra-core=1.3.2
  - pip:
      - wandb == 0.14.2
      - protobuf==3.20.*
      - hydra-joblib-launcher==1.2.0
